
http://localhost:3003/mission/all


###

post http://localhost:3003/mission/create
Content-Type: application/json


{
    "name":"Clarice Lispector",
    "start_date":"2021-02-25",
    "end_date":"2021-07-26",
    "type":"Noturna",
    "module": "1"
}
