###Get all mission
http://localhost:3003/mission/all

###Get all teacher
http://localhost:3003/teachers/all


### create mission
post http://localhost:3003/mission/create
Content-Type: application/json

{
    "name": "Murilo Rubião",
    "start_date":"21/01/2020",
    "end_date":"23/09/2020",
    "type":"Noturna",
    "module": "4"
    
}
### create teacher
post http://localhost:3003/teacher/new
Content-Type: application/json

{
    "name":"Darvino",
    "email": "darvas@gmail",
    "birthdate":"18/07/1993",
    "mission_id":3
}

### Criate student
post http://localhost:3003/student
Content-Type: application/json

{
    "name":"Vovó Juju",
    "email": "juju_abacate@gmail",
    "birthdate":"1934-02-30"
}